name: CombatLogger
version: '${version}'
main: org.bear.combatlogger.CombatLogger
api-version: '1.20'
commands:
  combatconfig:
    description: Used to edit the config of the combat logging mod
    usage: /combatconfig length <int>